version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin-spring
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    working_dir: /app
    restart: always

networks:
  default:
    external:
      name: db_net
